version: '3.1'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  pedido:
    image: pedidos
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

volumes:
  db: